### ISSUE TITLE
Regression: mate-power-manager, kde power manager fails (since patch 24)

### ISSUE THREAD

**Issue by mokraemer** [systemd/systemd-stable#447]
### systemd version the issue has been seen with

253

### Used distribution

Mageia 9

### Linux kernel version used

6.6.52-desktop-1.mga9

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

mate-power-manager should startup normally

### Unexpected behaviour you saw

it crashes like shown:
```
mate-power-manager 

(mate-power-manager:631002): PowerManager-ERROR **: 16:41:11.946: Error in dbus - GDBus.Error:System.Error.ESTALE: Stale file handle

```
[mga-bug](https://bugs.mageia.org/show_bug.cgi?id=33550)
[mate-bug](https://github.com/mate-desktop/mate-power-manager/issues/400)

### Steps to reproduce the problem

just compile patch version -24, even -25 does not correct the behaviour

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
#0  g_log_structured_array (log_level=<optimized out>, fields=0x7fffffffd430, n_fields=4) at ../glib/gmessages.c:555
        __func__ = "g_log_structured_array"
#1  0x00007ffff700d66e in g_log_default_handler
    (log_domain=log_domain@entry=0x41e974 "PowerManager", log_level=log_level@entry=6, message=message@entry=0x7fffe0002c40 "Error in dbus - GDBus.Error:System.Error.ESTALE: Stale file handle", unused_data=unused_data@entry=0x0)
    at ../glib/gmessages.c:3284

                    fields = {{key = 0x7ffff706952f "GLIB_OLD_LOG_API", value = 0x7ffff70671ac, length = -1}, {key = 0x7ffff7069445 "MESSAGE", value = 0x7fffe0002c40, length = -1}, {key = 0x7ffff7069458 "PRIORITY", value = 0x7ffff70627da, length = -1}, {key = 0x7ffff70694b2 "GLIB_DOMAIN", value = 0x41e974, length = -1}}
        n_fields = <optimized out>
#2  0x00007ffff700d8a8 in g_logv (log_domain=0x41e974 "PowerManager", log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=<optimized out>) at ../glib/gmessages.c:1391
        domain = 0x0
        data = 0x0
        depth = <optimized out>
        log_func = 0x7ffff700d5c0 <g_log_default_handler>
        domain_fatal_mask = <optimized out>
        masquerade_fatal = 0
        test_level = 6
        msg_alloc = 0x7fffe0002c40 "Error in dbus - GDBus.Error:System.Error.ESTALE: Stale file handle"
        msg = 0x7fffe0002c40 "Error in dbus - GDBus.Error:System.Error.ESTALE: Stale file handle"
        i = 2
#3  0x00007ffff700db52 in g_log (log_domain=log_domain@entry=0x41e974 "PowerManager", log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x41e025 "Error in dbus - %s") at ../glib/gmessages.c:1460
        args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffd650, reg_save_area = 0x7fffffffd590}}
#4  0x000000000040f908 in gpm_manager_systemd_inhibit (proxy=<optimized out>) at gpm-manager.c:1774
        fd = -1
        fd_list = 0x0
        arg_who = 0x644490 "marc"
        arg_why = 0x41f7d0 "Mate power manager handles these events"
        arg_mode = 0x41ee7c "block"
        error = 0x7fffe00025a0
        r = -1
        res = 0x0
        arg_what = 0x41f7f8 "handle-power-key:handle-suspend-key:handle-lid-switch"
        check_type_cpu = <optimized out>
        connection = 0x5244e8
        error = 0x0
#5  gpm_manager_init (manager=0x644460 [GpmManager]) at gpm-manager.c:1829
        check_type_cpu = <optimized out>
        connection = 0x5244e8
        error = 0x0
```

**Comment by mokraemer** [comment]
my assumption is, this patch introduced the problem:
[commit](https://github.com/systemd/systemd-stable/commit/75aefdd9c4c7cf1f75e6b1e43ab210f879c3b7e1)

**Comment by mokraemer** [comment]
confirmed. Reverting this patch, makes mate-power-manger work again.
